### PR TITLE
New UFC approach for F-15E

### PR DESCRIPTION
**Pull request by RafaPolit**
As documented in #171, the existing UFC approach presents:
- character lines
- special character lines, derived from the actual text from the character lines
- separated values for each extra property like `UFC_SC_02A`, `UFC_SC_05A`, etc.

This leaves the implementation of the UFC end result to the consumers of the DCS-BIOS data, which does not adhere to usual practices with DCS.

Also, there are errors in the algorithm (like replacing characters with spaces to extract the special characters)

This proposal (only applied to the FRONT UFC for the time being) is:
- to take a line-by-line approach (luckily there's only six)
- to include in the special characters in each line "parser" for easier reading
- take advantage of the fact that this extra keys appear to have a fixed location within the line (except for the user input line discussed later)
- most notable change is the inclusion of the user input from the keyboard into the Line 6 properties instead of leaving it as CC_04, which, again, left the implementation to the end user
- the center string is composed on TOP of the other strings and, if existing, takes precedence over everything else, to avoid problems
- the center string on the user input is not really "centered" but starts on a single digit.  Unfortunately, RAZBAMs implementation is not exactly matched with the existing digits and is slightly offset to the left, so I have assumed this starts on digit 6.  If and when RAZBAM fixes this and if it is found to be one digit to the right, changing it is a matter of changing a single number in the code.
- the center string on the user input is, apparently, the only place where the special character's strings `UFC_LL_INPUT_MIN` and `UFC_LL_INPUT_DEG` have a "conditional" placement based on user input.  I have added that logic only to Line 6 (which is part of the advantages of this approach, in my opinion), but should be easy to counter should RAZBAM decide to change or extend this logic.

This approach allows, as long as RAZBAM keeps the logic of the extra params to denote `°`, `.` and `:` as individual properties, to quickly include new additions into each line they belong to.

This also, I believe, deprecates the need for the "active radio", which I am uncertain why it was included.  If this is needed the logic needs to be ported to the new, and hopefully simpler, line structure.

I believe this is a good evolution, but maybe I missed something important that the previous implementation offered and I am really open to discussion and changes to the approach.

Should this be considered a good approach, extending it the rear UFC is literally adding 6 lines of code.

Hope this is useful, thanks as always for this incredible tool.

### CODE REVIEW

**Comment by Maverick87Shaka** [comment]
"Active radio" it's a workaround to have on a single display all the radio information, so you can check from one display if you have selected the manual frequency or a channel preset.

**Comment by Maverick87Shaka** [comment]
immagine

Not able to test current PR, doesn't work at all for me

**Comment by RafaPolit** [comment]
> "Active radio" it's a workaround to have on a single display all the radio information, so you can check from one display if you have selected the manual frequency or a channel preset.

I'll reintroduce this then.

**Comment by RafaPolit** [comment]
> immagine
> 
> Not able to test current PR, doesn't work at all for me

This apparently has nothing to do with my PR?  I re-downloaded the PR and install it afresh.  It did have an error lingering from the existing code that references the front UFC values in the rear UFC logic, so I have corrected that, but the error you report is probably not due to my commits?

If someone has any more feedback about what could this be I'd be happy to look into.  In the meantime, I'll reintroduce the active radio logic and see if that works.

**Comment by RafaPolit** [comment]
I have reintroduced the ActiveUHF 1 and 2, and, when the radio is off, this property outputs `R1 OFF` or `R2 OFF` mirroring L5 behavior.  If you want to show an empty string instead, let me know.

**Comment by Maverick87Shaka** [comment]
Downloaded now, 01 Jul 2023 @ 19:50 UTC, complete deleted prev. DCS-BIOS folder, using this PR, I can't get any display output.
No more error in dcs.log, dcs-bios is working, confirmed by other things working like LIGHT and LED indicator, but no display in any output.
immagine

**Comment by Maverick87Shaka** [comment]
...ok, it looks like it's a problem of the next build. I'll test later on current version and let you know. 
But I can't test it now

**Comment by Maverick87Shaka** [comment]
Tested on current OpenBeta works fine ( 2.8.6.41363 ).
Please just change initial variable length for active radio ( currently they are 10 chars ) and defined as 8 chars.
line 149/150 front ufc, 173/174 rear ufc.

**Comment by WarLord211** [comment]
and delete outcommanded or now unneeded lines

**Comment by RafaPolit** [comment]
Great.  Just to be sure, you prefer the radio set to 8 (which is the max length for their values) or reverted to the value of 10?

I will also extend the functionality to the Rear UFC and remove the unneeded previous implementation.

**Comment by Maverick87Shaka** [comment]
> Great. Just to be sure, you prefer the radio set to 8 (which is the max length for their values) or reverted to the value of 10?

10 was a "placeholder" that I've used since 10+10 should eventually cover all the display line (20), just in case, and eventually it will be also helpful if we want add later the * in the string, but since the functionality of this item, put the * in the string is useless, to me it's fine the length of 8, unfortunately it will cause address change from that line and below

**Comment by RafaPolit** [comment]
Since I'm removing all the 02A, 02B, 10SPA, 10SPB, 11SPA and 11SPB, all the addresses will change nonetheless.  I have no problem with either value, I'll just keep the 10 to keep it consistent.

**Comment by WarLord211** [comment]
perfect make the v Nr a 1.1 than i dont have to do it :)

**Comment by RafaPolit** [comment]
Alright, I think that's it:
- modified original `Active` strings to have 8 blank spaces (and kept the 8 as the property length)
- extended new functionality to rear UFC
- removed unneeded code
- upped version to 1.1

**Pull request merged**
