### PR TITLE
Add addresses header

### PR DESCRIPTION
**Pull request by maciekish**
This patch updates Protocol.lua to save address constants to doc\Addresses.h. This file can be included in the Arduino library to simplfy addressing.

Usage example:

```
void onIntCautionLBrightChange(unsigned int newValue) {
  analogWrite(13, newValue / (256 * 6));
}
DcsBios::IntegerBuffer intCautionLBrightBuffer(A_10C_INT_CAUTION_L_BRIGHT, onIntCautionLBrightChange);
```

Instead of:

```
void onIntCautionLBrightChange(unsigned int newValue) {
  analogWrite(13, newValue / (256 * 6));
}
DcsBios::IntegerBuffer intCautionLBrightBuffer(0x137a, 0xffff, 0, onIntCautionLBrightChange);

```

This is a snippet of the generated file:

```
#define A_10C_INT_CONSOLE_L_BRIGHT 0x1370, 0xFFFF, 0
#define A_10C_LCP_ACCEL_COMP 0x1144, 0x400, 10
#define A_10C_LCP_ENG_INST 0x1148, 0xFFFF, 0
#define A_10C_LCP_ANTICOLLISION 0x1144, 0x80, 7
#define A_10C_LCP_FLOOD 0x114E, 0xFFFF, 0
#define A_10C_LCP_FLIGHT_INST 0x114A, 0xFFFF, 0
```

### CODE REVIEW

**Comment by charliefoxtwo** [comment]
@WarLord211 this looks good to me and I think is a good addition - it should help make it easier for arduino users to update their code in the event the underlying addresses change.

**Comment by maciekish** [comment]
Also updated documentation to use the macros instead of addresses. Bort will need a separate PR if this is merged.

image

**Comment by maciekish** [comment]
Just noticed i missed some manual document{} statements in the actual aircraft definitions, thought it was all in Utils.lua. I'll try to update these later today.

**Comment by maciekish** [comment]
All done now.

**Comment by maciekish** [comment]
All done now.

**Pull request merged**
