### PR TITLE
Add Mi-24P PUVL & ASP17

### PR DESCRIPTION
**Pull request by charliefoxtwo**
I don't think this is exhaustive, but I've tested these to the best of my ability (except for the last two ASP17 lights) and I believe they're all working as expected.

### CODE REVIEW

**Comment by WarLord211** [comment]
if you would do more we should talkt that we no do something double

**Comment by charliefoxtwo** [comment]
Sounds good. Sorry if I stepped on some of your work! I don't have immediate plans to do more (I just had a thing that was dependent on this).

**Comment by charliefoxtwo** [comment]
Also, I noticed you made some changes to the bios ids I used. Totally fine - just curious, is there documentation somewhere on the preferred way to name these things? All of the files are rather inconsistent so I wasn't really sure what naming convention to use. Might be nice if that was defined somewhere (maybe it is, and I just couldn't find it).

If I make naming mistakes again, feel free to just request changes on the PR. I don't want to make more work for you by way of forcing you to fix my mistakes :)

If I were to do any panels next, it would be the pilot's forward-left-quarter panel with the autopilot and landing gear. Do you mind if I do that one next, or are you already working on it?

**Comment by WarLord211** [comment]
i do the naming my way ;)

**Comment by charliefoxtwo** [comment]
Well the naming changes you made to the stuff I did looked like it had a pattern to it. If I had known that was the preferred pattern it might have saved you some work :)

Just a suggestion, but it might be worth documenting that stuff in a `CONTRIBUTING.md` or similar. Things like:
 - The preferred pattern is `[ROLE]_[COMPONENT]_[LIGHT]_[CONTROL]_[COVER]`
    - when an aircraft has multiple roles, ids should be prefixed with the role (e.g. `PLT_`, `OP_`, `RIO_`)
       - if an aircraft does not have multiple roles, this segment should be omitted
    - lights should have an `L` before their descriptive name (e.g. `PLT_PUVL_L_RH_SIDE`)
       - if not a light control, this segment should be omitted
    - prefer `_CV` to `_COVER` for switch covers
       - if not a cover, this segment should be omitted
    - prefer `JETT` to `JETTISON`
 - try to keep names under _x_ characters by abbreviating parts of the id
 - others?
 
I have no problems with the way you do the naming :) But I think by documenting it, it will help others get the naming right the first time. And then if they get it wrong, you can point them to the documentation instead of having to fix it yourself. Your call though :)

**Comment by WarLord211** [comment]
i never hat help, so i had done all by myself and had no need to get an system in it beside that it looks good in my eyes.

**Comment by charliefoxtwo** [comment]
Alright, well if you want I'm happy to put that info in the readme or a contributing file or something and you can edit it as you see fit - just let me know.

Also do you mind if I start on the panel with the landing gear and autopilot controls or are you doing that one already?

**Comment by WarLord211** [comment]
i work from top to bottom. next is "ext lights"

**Comment by charliefoxtwo** [comment]
Gotcha, it looks like there's some space between the ext lights and the autopilot/spuu section, so I think we're fine there. The top of that panel does have nav lights/taxi lights/landing lights, so I'll just ignore those and leave them to you. I guess since you've handled cockpit mechanics looks like most of the gear stuff should be in.

So I'll take `autopilot` and `SPUU` next, if that's alright :)

**Comment by WarLord211** [comment]
jup

**Pull request merged**
